### ISSUE TITLE
DetailsBanner messes up positioning

### ISSUE THREAD

**Issue by willwull** [WatchItTeam/WatchIt#45]
So I was testing my DetailsTitle component (WIP) by putting it under an instance of DetailsBanner, but the `float: left` makes it appear above the title.

Here is a gif of me disabling `float`: https://imgur.com/OcNZhkz

Disabling it messes up the gradient position, so we need a better way to implement the banner.

**Comment by iRobsc** [comment]
Huh, that is weird. I guess I could make a small PR fix for this issue
