### ISSUE TITLE
Add button component

### ISSUE THREAD

**Issue by iRobsc** [WatchItTeam/WatchIt#9]
Looking at our concept art for the project we have some buttons in the sidebar. We could easily make these buttons a standalone component that can be re-used.

**Comment by iRobsc** [comment]
Since we have two different styles on the lists in the sidebar, they could still be the same component but have different kinds of css styling.

**Comment by willwull** [comment]
Not sure we need to make a specific component out of the links, we could probably just use the `NavLink` component from react-router (https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/NavLink.md)

**Comment by willwull** [comment]
Or maybe it's better to create a sort of wrapper component for the `NavLink` so we don't need to duplicate any classnames or stuff. Could look something like this maybe?

```js
function SidebarNavLink(props) {
  return <NavLink {...props} activeClassName="some-nice-class-name" />;
}
```
